# Generated by Django 4.1 on 2022-09-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastConnectedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_uid', models.CharField(max_length=20)),
                ('currently_connected', models.BooleanField(default=True)),
                ('connected', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNfcCard',
            fields=[
                ('username', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('card_uid', models.CharField(max_length=20, unique=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
