# Generated by Django 4.1 on 2022-09-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nfc_reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastconnectedcard',
            name='connected',
            field=models.DateTimeField(),
        ),
    ]
