# Generated by Django 4.1 on 2022-09-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nfc_reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentlyConnectedCard',
            fields=[
                ('card_uid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
